language: php
sudo: required
dist: trusty
php: 7.0
script:
 - wget https://github.com/magento/magento2/archive/2.1.4.zip
 - unzip -qq 2.1.4.zip
 - cd magento2-2.1.4/
 - composer require --no-interaction "monashee/smtp":"dev-master"
 - ls -al
 - ./vendor/bin/phpunit -c app/code/Monashee/Smtp/phpunit.xml.dist

